CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=70
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_CRITICAL=10
CONFIG_RGBLED_WIDGET_CONN_COLOR_ADVERTISING=7
CONFIG_RGBLED_WIDGET_CONN_COLOR_DISCONNECTED=5
# 增加最大组合设备数（左手+右手+电脑）
CONFIG_ZMK_MAX_COMBINED_SINK_LIST_LEN=3
# 启用 Dongle 模式相关的扫描逻辑
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
CONFIG_RGBLED_WIDGET=y
